-- Optional demo: tenant-style RLS using session GUCs set by PgGuard principal propagation.
-- Enable only when you want to exercise bearer_token → current_setting('app.user_id').
-- Off by default so existing demos keep full-table SELECT behavior.

-- Example (uncomment to enable):
-- ALTER TABLE corp.orders ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY orders_by_employee ON corp.orders
--   FOR ALL
--   TO app_reader, app_writer
--   USING (
--     employee_id::text = nullif(current_setting('app.user_id', true), '')
--     OR current_setting('app.user_id', true) IS NULL
--     OR current_setting('app.user_id', true) = ''
--   );
